import { Component, OnInit } from '@angular/core';
import { Observable, Subject } from 'rxjs';

@Component({
  selector: 'app-server-comm-demo',
  templateUrl: './server-comm-demo.component.html',
  styleUrls: ['./server-comm-demo.component.css']
})
export class ServerCommDemoComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  getdata()
  {
  //   let observableObj = new Observable( (subscriber) => {
  //     let x = 11;
  //    if(x % 2 == 0)
  //        subscriber.next("Data generated by observable -- " + x);
  //    else
  //        subscriber.error("Custom Error Message - Error Occurred while processing observable");
  //  });

  //  let o = new Observable();
  //  // subscribe or consuming observables
  //  observableObj.subscribe(
  //      (result:any) =>  {    console.log(result);   },
  //      (error:any) =>  {    console.log(error);   }
  //    );

    let subjectObj = new Subject();

    // First Subscriber
    subjectObj.subscribe((result) => {
          console.log("This is subscriber-1  :  " + result);
    });

    // Second Subscriber
    subjectObj.subscribe((result) => {
      console.log("This is subscriber-2  :  " + result);
    });


    subjectObj.next (  Math.random() );
    subjectObj.next ( "Message from Subject" );
  }

}
