var id = 5464654;
console.log("Employee Id : " + id);
var name1 = "Scott";
console.log("Employee Name :" + name1);
var job = "Manager";
console.log("Employee Job :" + job);
var per = true;
console.log("Is Permanent Employee : " + per);
var sal = 45000;
console.log("Employee Salary : INR. " + sal);
var dept = 10;
console.log("Employee Deptno :" + dept);
